version: "3.9"

services:
  backend:
    build: .
    container_name: besalco_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    container_name: besalco_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: besalco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: